apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: otel-demo
spec:
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100
      customTags:
        "open5gs":
          literal:
            value: "demo"
  accessLogging:
    - providers:
        - name: envoy
  metrics:
    - providers:
        - name: prometheus
